### ISSUE TITLE
[BUG] Attaching to running instance doesn't work (fzf-lua)

### ISSUE THREAD

**Issue by kapral18** [jbyuki/one-small-step-for-vimkind#45] opened 2024-05-19 14:26 UTC
I am using LazyVim which uses this setup https://github.com/LazyVim/LazyVim/blob/ad22adab7d446018875de2dc96168295cad9298e/lua/lazyvim/plugins/extras/dap/nlua.lua#L31

Here is my config on top:
https://github.com/kapral18/dotfiles/blob/ad539b7b57222293fdcae58fa2dde498789a34dd/home/dot_config/exact_nvim/exact_lua/exact_plugins/osv.lua

Initially I spotted the issue when trying to debug plugins inside lazy.nvim plugin folder, but to showcase the gist of it a simplified example will do as well.

1. I create `main.lua`:

```lua
local function test()
	print(1)
	print(2)
	print(3)
	print(4)
	print(5)
	print(6)
end

vim.keymap.set("n", "<Space>0", test, { buffer = true })
```

2. I run [`F5`](https://github.com/kapral18/dotfiles/blob/ad539b7b57222293fdcae58fa2dde498789a34dd/home/dot_config/exact_nvim/exact_lua/exact_plugins/osv.lua) from my config and see `Server started on port 8086`.

3. I open a second nvim instance with the same file, and set breakpoint on line 3 (with `print(2)`). 

4. Call nvim-dap continue and attach to 8086
![image](https://github.com/jbyuki/one-small-step-for-vimkind/assets/1625373/0544c97c-ca40-4604-afaa-007ace6c9135)

5. I see the message "Running: Attach to running Neovim instance" but couple of seconds later got a message about  debug adapter not responding
![image](https://github.com/jbyuki/one-small-step-for-vimkind/assets/1625373/9053ce55-9592-4ac4-8fff-3e1a7e771845)

6. I switch to debugee instance and run the file to make sure keymap is registered with `:luafile %`

7. I try the keymap and only see printed number in debuggee. Debugger doesn't respond. 

8. I exit debuggee instance and the debugger suddenly pops up the dap widget UI
![image](https://github.com/jbyuki/one-small-step-for-vimkind/assets/1625373/7d14f953-b540-4d1d-869c-6fce88a63ec4)

But at no point the breakpoint is caught.

**Comment by jbyuki** [comment] 2024-05-20 15:59
Thank you for opening an issue.

At first glance, I don't see what is wrong. The steps (which are nicely explained) seem to be correct. 

Could you try launching the server with logging enabled. This would translate to changing the following line in your config:

```lua
keys = {
    { "<F5>", [[:lua require"osv".launch({port = 8086, log=true})<CR>]], desc = "Launch OSV", noremap = true },
  },
```

This should output a log file within the nvim-data folder which can be found by running `:echo stdpath('data')`, it should be named `osv.log`. Please see there and post it if it can help.

**Comment by kapral18** [comment] 2024-05-20 23:14
@jbyuki 

After I invoked with logs and terminated debuggee I get this `osv.log`:

```log
{
  event = "terminated",
  seq = 1,
  type = "event"
}
{
  body = {
    exitCode = 0
  },
  event = "exited",
  seq = 2,
  type = "event"
}
{
  arguments = {
    adapterID = "nvim-dap",
    clientID = "neovim",
    clientName = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsProgressReporting = true,
    supportsRunInTerminalRequest = true,
    supportsStartDebuggingRequest = true,
    supportsVariableType = true
  },
  command = "initialize",
  seq = 1,
  type = "request"
}
```

**Comment by jbyuki** [comment] 2024-05-21 19:58
I still cannot pinpoint what is going on. I should have asked ealier but could you log nvim-dap as well?

https://github.com/mfussenegger/nvim-dap/blob/5a2f7121869394502521c52b2bc581ab22c69447/doc/dap.txt#L984-L1005

Maybe something to try would be to change the port. It may be a port blocking issue although I doubt it.
Also make sure to update the plugins. And what is your OS/nvim version?

**Comment by jbyuki** [comment] 2024-05-21 20:15
It would be awesome if you could log `osv` again. I just added a new commit to make a more exhaustive log.

**Comment by kapral18** [comment] 2024-05-22 10:04
MacOS Sonoma 14.5

NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info

For some reason I didn't get any dap.log after setting the log to trace.

`osv.log`

{
  event = "terminated",
  seq = 1,
  type = "event"
}
{
  body = {
    exitCode = 0
  },
  event = "exited",
  seq = 2,
  type = "event"
}
{
  arguments = {
    adapterID = "nvim-dap",
    clientID = "neovim",
    clientName = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsProgressReporting = true,
    supportsRunInTerminalRequest = true,
    supportsStartDebuggingRequest = true,
    supportsVariableType = true
  },
  command = "initialize",
  seq = 1,
  type = "request"
}
{
  arguments = {
    adapterID = "nvim-dap",
    clientID = "neovim",
    clientName = "neovim",
    columnsStartAt1 = true,
    linesStartAt1 = true,
    locale = "en_US.UTF-8",
    pathFormat = "path",
    supportsProgressReporting = true,
    supportsRunInTerminalRequest = true,
    supportsStartDebuggingRequest = true,
    supportsVariableType = true
  },
  command = "initialize",
  seq = 1,
  type = "request"
}
{
  body = {
    supportTerminateDebuggee = true,
    supportsConditionalBreakpoints = true,
    supportsHitConditionalBreakpoints = true,
    supportsSetVariable = true
  },
  command = "initialize",
  request_seq = 1,
  seq = 1,
  success = true,
  type = "response"
}
{
  event = "initialized",
  seq = 2,
  type = "event"
}

**Comment by jbyuki** [comment] 2024-05-22 10:15
I will get back later but make sure to check
`vim.fn.stdpath('cache')`. It is not the same folder as the one used by `osv`, it should be there.

**Comment by kapral18** [comment] 2024-05-22 11:21
you are right my bad

here is the file

```log

[ INFO ] 2024-05-19T01:52:10Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ INFO ] 2024-05-19T01:53:00Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ INFO ] 2024-05-19T01:54:09Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ INFO ] 2024-05-19T01:55:30Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ INFO ] 2024-05-19T01:56:02Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ INFO ] 2024-05-19T01:56:03Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ INFO ] 2024-05-19T01:56:05Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"


[ INFO ] 2024-05-19T02:20:18Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ ERROR ] 2024-05-19T02:20:44Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:965 ]	"No callback found. Did the debug adapter send duplicate responses?"	{
  body = {
    supportTerminateDebuggee = true,
    supportsConditionalBreakpoints = true,
    supportsHitConditionalBreakpoints = true,
    supportsSetVariable = true
  },
  command = "initialize",
  request_seq = 1,
  seq = 3,
  success = true,
  type = "response"
}

[ INFO ] 2024-05-19T02:26:47Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"

[ INFO ] 2024-05-19T02:57:52Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ INFO ] 2024-05-19T02:58:20Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ INFO ] 2024-05-19T02:58:23Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ INFO ] 2024-05-19T02:59:44Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"




[ INFO ] 2024-05-19T16:20:02Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ INFO ] 2024-05-19T16:23:03Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"
[ ERROR ] 2024-05-19T16:23:21Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:965 ]	"No callback found. Did the debug adapter send duplicate responses?"	{
  body = {
    supportTerminateDebuggee = true,
    supportsConditionalBreakpoints = true,
    supportsHitConditionalBreakpoints = true,
    supportsSetVariable = true
  },
  command = "initialize",
  request_seq = 1,
  seq = 3,
  success = true,
  type = "response"
}
[ ERROR ] 2024-05-19T16:23:21Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:965 ]	"No callback found. Did the debug adapter send duplicate responses?"	{
  body = {
    supportTerminateDebuggee = true,
    supportsConditionalBreakpoints = true,
    supportsHitConditionalBreakpoints = true,
    supportsSetVariable = true
  },
  command = "initialize",
  request_seq = 1,
  seq = 5,
  success = true,
  type = "response"
}



[ INFO ] 2024-05-22T12:01:03Z+0200 ] ...al18/.local/share/nvim/lazy/nvim-dap/lua/dap/session.lua:1812 ]	"Session closed due to disconnect"


```

**Comment by jbyuki** [comment] 2024-05-22 18:51
Would running this help before running `launch()`.

```lua
:lua require"osv".stop = function() end
```

Then execute `launch` and the rest. This should avoid the early exit which is happening for some reason.

**Comment by jbyuki** [comment] 2024-05-22 19:10
I just had a look in the config you linked. From the look of it, there is a substantial amount of plugin installed. I wouldn't be suprised if something is interacting together with `osv` in a bad way. The best would be to disable all plugins except a few ones and try. Thus by successive disabling/enabling, you could pinpoint what is going wrong. The plugin `osv`

**Comment by kapral18** [comment] 2024-05-22 19:14
> Would running this help before running `launch()`.
> 
> ```lua
> :lua require"osv".stop = function() end
> ```
> 
> Then execute `launch` and the rest. This should avoid the early exit which is happening for some reason.

this didn't work

**Comment by kapral18** [comment] 2024-05-22 19:14
> I just had a look in the config you linked. From the look of it, there is a substantial amount of plugin installed. I wouldn't be suprised if something is interacting together with `osv` in a bad way. The best would be to disable all plugins except a few ones and try. Thus by successive disabling/enabling, you could pinpoint what is going wrong. This is a standard practice for debugging plugins. The plugin `osv` is supposed to work with `nvim-dap`.
> 
> Another possibility is the OS which I cannot test right now.

I will check with vanilla lazyvim starter then

**Comment by kapral18** [comment] 2024-05-22 20:33
Ok I checked. It wasn't neovim. But I found the issue the issue is this call https://github.com/kapral18/dotfiles/blob/ad539b7b57222293fdcae58fa2dde498789a34dd/home/dot_config/exact_nvim/exact_lua/exact_plugins/fzf.lua#L339

and I mean just the require, not the references, because I commented all them out and it hangs precisely on this require call. Something apparently happens inside fzf-lua actions that causes the osv to hang.

Not sure but maybe @ibhagwan has an idea?

**Comment by jbyuki** [comment] 2024-05-22 20:50
Interesting. It was not known that `fzf-lua` had issues with `osv`

The problem is that probably someone needs to know the inner workings of both `osv` and `fzf-lua` which is most likely an empty set right now.

I don't follow how you pinpointed the error but it would be nice to pinpoint it further. So the require means it's inside this file actions.lua of fzf-lua when it's first executed. Which could be inside the utils.lua which is in turn required, possibly.

**Comment by ibhagwan** [comment] 2024-05-22 21:08
The only thing I can think of is the overload of the `require` method in headless instances as part of the fzf-lua libuv command proxy.

https://github.com/ibhagwan/fzf-lua/blob/e65b86532380c4e60490bc19b647d0c4faa58096/lua/fzf-lua/libuv.lua#L16

It is possible that since you’re loading `fzf-lua.actions` file directly the global fzf directory var isn’t being set causing libuv to think it’s running the command wrapper.

You can try changing the actions require to `require'fzf.lua'.actions` (so the code calls `init.lua` first) or just add `require'fzf.lua'` in the line above the line you linked?

**Comment by kapral18** [comment] 2024-05-23 06:54
hey @ibhagwan you absolutely hit the nail on the head, I can confirm that with `require'fzf-lua'.actions` it works again

**Comment by ibhagwan** [comment] 2024-05-23 09:56
> hey @ibhagwan you absolutely hit the nail on the head, I can confirm that with `require'fzf-lua'.actions` it works again

Great!

I think I might add a global so this doesn’t happen even in this extreme edge cases.

**Comment by jbyuki** [comment] 2024-05-23 16:43
@ibhagwan Thanks for the input! Glad this was sorted out. I will add a small note in the readme in case someone has the same issue.

@kapral18 I will close this issue now as it looks solved.

**Closed by jbyuki** 2024-05-23 16:43 UTC

**Comment by ibhagwan** [comment] 2024-05-23 16:52
Tysm @jbyuki! And ty @kapral18 for great debugging.
